# for local testing
services:
  attachment-converter:
    build: .
    volumes:
      - ./testfolder:/app/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OUTPUT_FORMATS=webp,avif
#      - DEBUG=true
    tty: true
