name: Code Metrics Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-metrics:
    name: Analyze Code Metrics
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0 # Adjust version as per your project needs

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Run the .NET code metric analyzer
      - name: .NET Code Metric Analyzer
        uses: MarvinDrude/DotNet.GitHubActionMetrics@Deployment
        with:
          dir: . # Specify the root directory or adjust based on your solution/project location
